apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Kompose\kompose.exe convert
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: magento
  name: magento
spec:
  type: LoadBalancer
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    io.kompose.service: magento
